### ISSUE TITLE
Failed to load resnet50_ibn_a_80.pth model

### ISSUE THREAD

**Issue by ganler** [heshuting555/AICITY2020_DMT_VehicleReID#13]
Hi there,

I was trying your pre-trained model(resnet50_ibn_a_80.pth: https://drive.google.com/file/d/14TTv8mEECkRLgtmmTMY9BPc70rhgmXcu/view?usp=sharing) using configuration: `configs/baseline_veri_r50_a.yml`. 

And I made some little modification as I don't want to train it.

```
import os
from config import cfg
import argparse
from model import make_model


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="ReID Baseline Training")
    parser.add_argument(
        "--config_file", default="configs/baseline_veri_r50_a.yml", help="path to config file", type=str
    )
    parser.add_argument("opts", help="Modify config options using the command-line", default=None,
                        nargs=argparse.REMAINDER)

    args = parser.parse_args()



    if args.config_file != "":
        cfg.merge_from_file(args.config_file)
    cfg.merge_from_list(args.opts)
    cfg.freeze()

    os.environ['CUDA_VISIBLE_DEVICES'] = cfg.MODEL.DEVICE_ID

    # train_loader, val_loader, num_query, num_classes = make_dataloader(cfg)
    model = make_model(cfg, num_class=80)
    model.load_param('resnet50_ibn_a_80.pth')

    with torch.no_grad():
        print(model(torch.zeros((1, 3, 224, 224))).shape)
```

However, I cannot load your model. The logging loads like this:

```
using resnet50_ibn_a as a backbone
Traceback (most recent call last):
  File "try.py", line 30, in <module>
    model = make_model(cfg, num_class=80)
  File "AICITY2020_DMT_VehicleReID/model/make_model.py", line 124, in make_model
    model = Backbone(num_class, cfg)
  File "AICITY2020_DMT_VehicleReID/model/make_model.py", line 66, in __init__
    self.base.load_param(model_path)
  File "AICITY2020_DMT_VehicleReID/model/backbones/resnet_ibn_a.py", line 164, in load_param
    self.state_dict()[i.replace('module.','')].copy_(param_dict[i])
KeyError: 'base.conv1.weight'
```

Do you have any idea of what is going on? Thanks for your help in advance.

**Comment by heshuting555** [comment]
you can change `self.state_dict()[i.replace('module.','')].copy_(param_dict[i])`
to `self.state_dict()[i].copy_(param_dict[i])`
