### ISSUE TITLE
 No such file or directory：  AIC20_track2/AIC20_ReID/train_track_id.txt

### ISSUE THREAD

**Issue by shenwenxiao** [heshuting555/AICITY2020_DMT_VehicleReID#22]
您好，
我在跑您的算法AICITY2020_DMT_VehicleReID的时候
执行test.py文件，报错Traceback (most recent call last):
  File "/media/zq/train/code2/AICITY2020/test.py", line 43, in <module>
    train_loader, val_loader, num_query, num_classes = make_dataloader(cfg)
  File "/media/zq/train/code2/AICITY2020/datasets/make_dataloader.py", line 53, in make_dataloader
    dataset = __factory[cfg.DATASETS.NAMES](root=cfg.DATASETS.ROOT_DIR, plus_num_id=cfg.DATASETS.PLUS_NUM_ID)
  File "/media/zq/train/code2/AICITY2020/datasets/aic_aicsim.py", line 31, in __init__
    train = self._process_dir(self.train_dir, relabel=True)
  File "/media/zq/train/code2/AICITY2020/datasets/aic_aicsim.py", line 71, in _process_dir
    _, _, frame2trackID = self._process_track(path=self.train_track_path) #### Revised
  File "/media/zq/train/code2/AICITY2020/datasets/aic_aicsim.py", line 121, in _process_track
    file = open(path)
FileNotFoundError: [Errno 2] No such file or directory: '/media/zq/train/code2/data/AIC20_track2/AIC20_ReID/train_track_id.txt'
模型是您的预训练模型final_model/0409_3/resnet101_ibn_a_70.pth
cfg文件是 configs/baseline_aic_se.yml
这个train_track_id.txt文件是干啥的呀
为什么为执行测试命令，还需要train的文件

我下载的数据集是2021版本的，是因为数据集2020和2021的版本不一样吗？

**Comment by heshuting555** [comment]
2021比赛我们也开源了代码，可以参考这里：
https://github.com/michuanhaohao/AICITY2021_Track2_DMT
